// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djmxenancvnccinyducn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbXhlbmFuY3ZuY2NpbnlkdWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MjA1NTcsImV4cCI6MjA2MzI5NjU1N30.NyPHTqg17r3HsUBhV5FDQhoBZF2xbupCyrqhv15jiag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);